### ISSUE TITLE
Multiple quit requester.

### ISSUE THREAD

**Issue by T0lk13n** [chris-y/avalanche#11]
If you click two or more times in the quit gadget you will get two or more times a Quit requester that need to close before Avalanche gets closed.

**Comment by chris-y** [comment]
I think this is just event queuing isn't it?  Or are you getting the Quit requesters at the same time - as I can't reproduce that.

**Comment by T0lk13n** [comment]
First, Im using an A1260 with AOS 3.2.1.
I click in the Quit gadget and the Quit Requester appears. I ignore it and click again in the Quit gadget.
Then I close the Quit requester and appear another Quit requester that have to close to can end with Avalanche.
Hope I have explained better.

**Comment by chris-y** [comment]
Yes, that's usual Intuition behaviour 🙂, it queues up the input events until the program fetches them - in this case, they get fetched after the requester closes (it suspends the main application whilst it is open).  It shouldn't be asking again if you've already said to quit on the first one though - that is a bug.
