### ISSUE TITLE
Locale support

### ISSUE THREAD

**Issue by samo79** [chris-y/avalanche#13]
Add localization support :-)

**Comment by samo79** [comment]
Hi.. i've done the translation and tested it with that new binary but it doesn't seems to work
Attached the translation file

Btw, i know it's an extra boring work but isn't better to include aniway that translations in main archive?

[avalanche_ITA.zip](https://github.com/chris-y/avalanche/files/8742353/avalanche_ITA.zip)

**Comment by chris-y** [comment]
I've fixed that issue, catalog now working as expected.

As to your other point, in theory it's better, but all it really means is I'm chasing people for translations before I can release anything and/or the translations in the package are out-of-date. I've done this before so I know what hassle it is. I'd rather keep them separate so they can be updated when the maintainer has time, without me being involved.
