### ISSUE TITLE
Save window position broken?

### ISSUE THREAD

**Issue by samo79** [chris-y/avalanche#17]
The option "Save window position" doesn't seems to work... if i set it and then restart Avalanche, the window will the reopened by default in the save position and the same default size

**Comment by chris-y** [comment]
Also, can you save and post the tooltypes?

**Comment by samo79** [comment]
Yeah you are right, i didn't save the settings before quit .. :-)
Parhaps this save position settings could be enabled by default?

You can close the ticket aniway

P.S.
I'm using AmigaOS 4.1 FE
