### ISSUE TITLE
Unknown filesystem string

### ISSUE THREAD

**Issue by samo790** [chris-y/avalanche#29]
The "Unknown filesystem" string is missed from the catalog descriptor of translation

**Comment by chris-y** [comment]
This message comes from xadmaster.library.  I'm not sure how localised that is, but please raise a bug report over there (although I'm not sure where it's hosted now as the project seems to have disappeared from sf.net)

**Comment by samo790** [comment]
Maybe here:
https://github.com/ashang/libxad

But there are no translation files there and as you says the account on SF gone, or was moved elsewhere
