### ISSUE TITLE
"Out of memory scanning file" when unpacking NDK3.2.lha

### ISSUE THREAD

**Issue by rosneru** [chris-y/avalanche#30]
I've used Avalanche successfully with many lha files.

But with the `NDK3.2.lha` from Aminet there's an *Out of memory scanning file* error requester shown when halfway trough.

I tested it on an WinUAE-emulated A1200 with OS 3.2.1, 68040, 128 + 2 MB RAM.

**Comment by chris-y** [comment]
Can reproduce on OS4, happens on three files but not sure which ones.  Unlikely it is actually running out of memory.  Need to get this to report the filename in order to investigate further.

**Comment by chris-y** [comment]
Added filename to error requester.  This error appears when memory allocation fails - within Avalanche, not xvs.library.
I've changed the allocation to MEMF_PRIVATE and the error has disappeared.  This is not a solution for OS3.2 though - I will test again there.

**Comment by chris-y** [comment]
Another test archive: https://aminet.net/text/misc/grep-2.5-bin-m68k.lha

**Comment by chris-y** [comment]
The grep issue appears to be that some files are 0 bytes.

**Comment by chris-y** [comment]
Tested with latest OS3 build and confirmed fixed.
