### ISSUE TITLE
Extremely slow ASL file requester

### ISSUE THREAD

**Issue by kowoba** [chris-y/avalanche#39]
The ASL file requester to pick an archive in Avalanche is just crazy slow compared to, for example, C:RequesFile or open file in just about all other programs that use ASL.

**Comment by chris-y** [comment]
It uses a hook to identify archives - this makes it slow but stops unreadable files from showing up.

**Comment by kowoba** [comment]
Good grief…. 😮
Please add an option/tooltype that turns off this "feature", I already know which files are archives or not.

**Comment by chris-y** [comment]
Easily done - added NOASLHOOK tooltype for next version.
