### ISSUE TITLE
Cant delete first used file

### ISSUE THREAD

**Issue by T0lk13n** [chris-y/avalanche#40]
I am using Avalanche 1.8 in Amiga 1200 060 with aos 3.2.1.
I have a bunch of lha that are extracted to ram:
When I double click in a LHA it open Avalanche so I have only click in Extract button.
All goes ok but the problem is when I want to delete the lha files.
I can delete all of them but the first one I used to extract. It seems locked.
I have to reboot and then I can delete it.

**Comment by chris-y** [comment]
Does this still happen if you only open that one file, extract and quit?

**Comment by T0lk13n** [comment]
Just tested now...Yes, It happends too.

**Comment by chris-y** [comment]
OK, and it's only if you double-click the file to open it?  If you open in the GUI it can be deleted? (please try both with the file open button, and by dragging the file in)
If you open Avalanche and then click the file and select Tools => Extract here, can it be deleted then?

I've scanned through the code and can't see any locks being held so trying to figure out where it is likely to be going wrong.

**Comment by chris-y** [comment]
OK, thanks, I think I know what is causing this now - the window isn't being disposed and therefore the archive isn't being closed.
As a final test, can you extract then pick Project=>Quit, and see if you can then delete the file (that will be the workaround for now!)

**Comment by T0lk13n** [comment]
Oh yes! 
From Project->quit it works good and can delete the file.

**Comment by chris-y** [comment]
Ace!  Yes, the first window acts a bit differently and the program no longer quits when it is closed (I would change that but because it's the first window opened rather than the last one still open, it gets complicated)

Quick fix = move archive close into window_close and refresh on window_open
Better long term fix = stop treating the first window as a special case

**Comment by chris-y** [comment]
Tested and confirmed fixed.
