### ISSUE TITLE
Overwrite requester

### ISSUE THREAD

**Issue by MM-Mikhail** [chris-y/avalanche#7]
Missing ability to overwrite files if they already exist, or skip.

Also missing ability to abort operations.

**Comment by chris-y** [comment]
Aborting requires the use of XAD hooks.

- [ ] Support XAD hooks
- [ ] Add Cancel button
- [ ] Support overwriting existing files

**Comment by chris-y** [comment]
Looks like the progress hook is needed for both cancel and overwrite.

**Comment by chris-y** [comment]
Need to be more careful with my commit message phrasing :)
